### ISSUE TITLE
Tensorboard Logging

### ISSUE THREAD

**Issue by mohakbhardwaj** [marc-rigter/rambo#2]
Hello, 
I am trying to run RAMBO on `halfcheetah-medium` using `run_example.sh`. However, the log file produced in `./logs` directory has a size of 0KB even after two hours of training, and tensorboard does not show any plots. Is there a way to debug why this is the case? I tried running `hopper-medium` as well and the issue remains. Thanks!

**Comment by marc-rigter** [comment]
Hi, 
Thanks for pointing out this issue. I realised that I did not set up the code to also correctly log to Tensorboard (I used Weights and Biases for my experiments). This issue should be corrected in the most recent commit b4d8dd5, so it should work now. There is the pretraining phase (where the model is initially trained with supervised learning only) that can take a couple of hours and no data is logged, so it might still take a little while before data starts being logged.

Cheers,

Marc
